name: Barton Beebe's Open Source Trademark Casebook
markdown: redcarpet
highlighter: true
# Change url to your domain. Leave localhost server or blank when working locally.
url: #              http://adlervermillion.com 



include: [".htaccess", "_pages", "MPEP", "pages"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", 'pixelmator_files', 'drafts']
